title: Pfim
description: >
   Fast .NET image decoder for targa (.tga) and direct draw surface (.dds) images
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
