title: Pfim
description: >
   C# fast image decoder that can work targa (.tga) and direct draw surface (.dds) images
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
